plugins {
    // 📄 PERBAIKAN: Tambahkan versi plugin secara eksplisit di sini
    id 'com.android.application' version '8.2.2'
}

android {
    namespace "com.ah.mad.dola.app"
    compileSdk = 34
    buildToolsVersion = "34.0.0"

    defaultConfig {
        applicationId "com.ah.mad.dola.app"
        minSdk 21
        targetSdk 31
        versionCode 1
        versionName "1.0"
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.11.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
}
